### ISSUE TITLE
Folder structure

### ISSUE THREAD

**Issue by abhirock1998** [koders-in/Website#17]
- [ ] use assets folder for fonts, images, and  all other media
- [ ] export all components from the single file as a dictionary
- [ ] create config.json file for contact, link, and other constant variables

**Comment by valasubramanian-tw** [comment]
@1stdevfriend I would like to work on this issue. Can you assign it to me?

**Comment by 1stdevfriend** [comment]
Let's complete other issues first :) Already things are on your plate.

**Comment by anil-muraleedharan** [comment]
Hi, I would like to work on this issue, could you assign this to me?

**Comment by 1stdevfriend** [comment]
Sure! @anil-muraleedharan

**Comment by anil-muraleedharan** [comment]
@abhirock1998 One small clarification on the first subtask, while moving the images to assets folder where should we keep the assets folder? Should it be inside public or src?

Option 1:  public > assets > images

Option 2: src > assets > images

I am little inclined towards the first option since the images or any other medias are not exactly source files

**Comment by 1stdevfriend** [comment]
Hey hi @anil-muraleedharan 

Prefer option 2 as we do handle assets in the same way only :)

Tag me if you need anything else you know

**Comment by anil-muraleedharan** [comment]
Thanks for the clarification @1stdevfriend , I will raise the PR for the first task
