### ISSUE TITLE
Responsiveness issues of all pages

### ISSUE THREAD

**Issue by abhirock1998** [koders-in/Website#19]
- [ ] Add responsiveness to all pages for all devices
- [ ] Kareer page image overflow
- [ ] Fix header issues for all devices
- [ ] Blog page header background is not matched with other pages
- [ ] Fix portfolio page project section margin, padding
- [ ] look into the testimonial parts section of the home page  for all device
- [ ] Change the cursor style for better UX because sometimes it feels like it lags or hangs

**Comment by sudhinm** [comment]
Can I work on this?

**Comment by Smodi16** [comment]
Sure @sudhinm

**Comment by 1stdevfriend** [comment]
@sudhinm Is there anything left?

**Comment by sudhinm** [comment]
@1stdevfriend There are few minor issues pending which I'll fix soon.

- [x] Add responsiveness to all pages for all devices
- [x]  Kareer page image overflow
- [ ]  Fix header issues for all devices
- [ ]  Blog page header background is not matched with other pages
- [x]  Fix portfolio page project section margin, padding
- [x]  look into the testimonial parts section of the home page for all device
- [ ]  Change the cursor style for better UX because sometimes it feels like it lags or hangs

**Comment by sudhinm** [comment]
@1stdevfriend All the items are fixed as part of this issue. Please review it once and merge if possible.

- [x] Add responsiveness to all pages for all devices
- [x]  Kareer page image overflow
- [x]  Fix header issues for all devices
- [x]  Blog page header background is not matched with other pages
- [x]  Fix portfolio page project section margin, padding
- [x]  look into the testimonial parts section of the home page for all device
- [x]  Change the cursor style for better UX because sometimes it feels like it lags or hangs

**Comment by 1stdevfriend** [comment]
Great work! Feel free to work on our insider website at https://github.com/koders-in/website-insider or apply at koders via info@koders.in :)
